CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE short_urls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  short_code VARCHAR(32) NOT NULL UNIQUE,
  original_url VARCHAR(4000) NOT NULL,
  click_count BIGINT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  expires_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_short_urls_user
    FOREIGN KEY (user_id)
    REFERENCES users(id),
  CONSTRAINT chk_short_urls_status
    CHECK (status IN ('active', 'disabled', 'expired'))
);

CREATE INDEX idx_short_urls_user
  ON short_urls(user_id);

CREATE TABLE clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  short_url_id BIGINT NOT NULL,
  clicked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_agent VARCHAR(1000),
  referrer VARCHAR(2000),
  CONSTRAINT fk_clicks_short_url
    FOREIGN KEY (short_url_id)
    REFERENCES short_urls(id)
);

CREATE INDEX idx_clicks_short_url
  ON clicks(short_url_id);

CREATE INDEX idx_clicks_time
  ON clicks(clicked_at);